pipeline {
  agent { label 'principal' }
  environment {
    appName = "variable" 
  }
  stages {

 stage("paso 1"){
     
      steps {	
            echo 'hola mundo'
      }
    }
  }
  post {
      always {          
          deleteDir()
           echo 'fase always'
      }
      success {
             echo 'fase success'
        }

      failure {
             echo 'fase failure'
      }
      
  }
}  

